# Generated by Django 4.1.6 on 2024-03-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_brandimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandimage',
            old_name='product',
            new_name='name',
        ),
    ]
