# Generated by Django 4.1.6 on 2024-03-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_product_brandimage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandimage',
            old_name='name',
            new_name='brand',
        ),
    ]
