# Generated by Django 4.2.11 on 2024-03-17 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customer_user_delete_adm_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adm',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Adm', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('adm_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Cliente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('payment_info', models.CharField(max_length=100)),
                ('customer_id', models.IntegerField()),
            ],
        ),
    ]
