# Generated by Django 4.2.11 on 2024-03-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_adm_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
