# Generated by Django 4.1.6 on 2024-03-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
